### ISSUE TITLE
Routing to subpages of subpages

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-explorer#101]
On the develop branch, there are five main menu items.

The first one, Dashboard, has five tabs: Overview, Accounts, Monitors, etc.

The second tab, Accounts, is supposed to have sub-tabs which display vertically for various things (Transactions, Functions, Neighbors, Tokens, Accounting, etc. -- only Transactions and Functions show now -- names are not finalized.)

I can get the tabs to work, etc, but I can't seem to get the routing to work. When I click on Accounts, it properly goes to the Accounts tab, but when I click on any of the sub-tabs (Transactions or Functions), it returns to the Overview tab.

I can't really figure out how to make this work.

We can discuss later if this mode (sub-tabs within tabs) is a good UI choice, but for now, let's just get it to work so we can see the data we have to deal with. Fixing the actual structure of the UI can wait a bit.

**Comment by deeayeen** [comment]
https://github.com/TrueBlocks/trueblocks-explorer/pull/107
