### ISSUE TITLE
1.0 Why does the Accounts tab re-fetch the data each time I click on a new subtab?

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-explorer#110]
We discussed this in the call.

We were wondering why the fetch to get the transactional history was being re-initiated each time I click on a sub tab (Transactions, Functions, Events) under the Accounts tab.

We traced it down to the use of a new DashboardView in each route.

It would be great if the transactional data was only fetched the first time the user opens the Accounts view.

We can worry about rendering fresh (even pending) transactions later and when we do only fetch new data since the last fetch for a given address.

For now, just avoid reloading the entire fetch each time the tab changes.

It would be interesting to do the same even if the user clicked off to some totally different view (for example, the block explorer) -- upon return -- it would be good to still have the same account transaction data in memory.

**Comment by deeayeen** [comment]
This would require putting it in the global state

**Comment by tjayrush** [comment]
Yes. I think that's what would be required. I think there's going to be at least three things in the global state:

1) The 'status' query (which gets reloaded peridocially)
2) Names
3) Active Account Transactions (which may also get appended to periodically)

**Comment by tjayrush** [comment]
This is now completed. Thanks.
