### ISSUE TITLE
Taking arbitrary addresses in the route for the Accounts tab

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-explorer#111]
Currently, I have the account address hard coded in the AccountsView component: https://github.com/TrueBlocks/trueblocks-explorer/blob/develop/src/ui/views/Dashboard/Tabs/Accounts/Accounts.tsx#L18

I did this only because I don't know how to pass parameters around using routes between components.

We can close this issue when we can do the following:

1. Go to Dashboard / Monitors view
2. Double click on one of the monitors (if there are none, go to the command line and enter `chifra list` and wait until it completes -- reload the Monitors view and that monitor should show up.)
3. Upon double click, open the Accounts tab using the double clicked address instead of the hard coded address above.

**Comment by deeayeen** [comment]
https://github.com/TrueBlocks/trueblocks-explorer/pull/113

**Comment by tjayrush** [comment]
The double click is not yet working, but the basic methodology is, so I'll close this.
