### ISSUE TITLE
Querying for the number of records in a monitor

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-explorer#121]
We need to know the number of records to expect from the backend of a given monitor in order to do progressive querying for the actual transaction data.

That can be done with this curl command:

```
curl "http://localhost:8080/export?addrs=<addr>&count"
```

The value you're looking for appears in `.data[0].nRecords`.

**Comment by deeayeen** [comment]
I see you wrote export, when earlier in the code you wrote instead the list command

http://localhost:8080/list?count&appearances&addrs=0xf503017d7baf7fbc0fff7492b751025c6a78179b

I'm currently using the list command and it's working well
