### ISSUE TITLE
0.0 Make names data a global state thing

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-explorer#125]
Initially, it will be an array, so your code needs to make it a map.

Usage

```
const names = useNames()

<div>{names[tx.addr]}</div>

```

**Comment by deeayeen** [comment]
https://github.com/TrueBlocks/trueblocks-explorer/pull/128

**Comment by deeayeen** [comment]
```
const { names } = useGlobalState()

const desiredAddressName = names[address]
```

**Comment by tjayrush** [comment]
This works wonderfully. It's merged into `develop` branch. You should check it out.
