### ISSUE TITLE
Required / default fields on Add Name / Edit Name

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-explorer#140]
**These fields are required and may not be empty:**
Address (must be a valid 42 character string with leading 0x -- upper case / lower case does not matter)
Name (cannot be empty)

**These fields are required, but may be defaulted:**
Source (defaults to EtherScan.io -- or maybe Self Entered)

**This field could display a dropdown of existing with ability to add new**
Tags

**Not required - may be empty:**
Description

**Comment by deeayeen** [comment]
https://github.com/TrueBlocks/trueblocks-explorer/pull/153
