### ISSUE TITLE
At Your Leisure: Enable Charts View under Dashboard / Account Detail

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-explorer#141]
See these definitions of the data types:

https://github.com/TrueBlocks/trueblocks-explorer/tree/master/src/ui/modules/types

In particular, `Transaction` and `Reconciliation`.

You will see that every transaction has an array of Reconciliations called statements. Each statement has two fields of interest: `assetSymbol` and `endBal`.

Under the Charts subtab under the Account Detail tab of the Dashboard view, I invite you to show, for each different asset, a chart of the historical balances for that asset.

I envision a dropdown that lists all the assetSymbols available in a given account's history that allows the user to select different assets to view.

**Comment by deeayeen** [comment]
https://github.com/TrueBlocks/trueblocks-explorer/pull/146

**Comment by deeayeen** [comment]
https://github.com/TrueBlocks/trueblocks-explorer/pull/148

**Comment by tjayrush** [comment]
I'm going to close this one as it mostly works as I wish. We spoke about some additions, but I can do them later.
