### ISSUE TITLE
Remove `types` data from JSON produced for the front end

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-explorer#186]
Currently, all of the data produced for the front end through the API server attaches a field called `types`.

```
{
  "data": [],
  "types": [],
  "meta": []
}
```

I'm 99.9% sure it's not used in the front end, and I am 100% certain it's not used in the backend. As part of the New Chifra work, I want to remove it.

This issue is here to give @dszlachta a chance to voice his opinion. Do we need this `types` data? I don't think so as we are currently using TypeScript.

It was originally added about three years ago when I first start the JavaScript project because I couldn't live without types, but now I think it's not needed.

Say 'yes' and I will remove it from the backend. You may close this issue when you repsond.

**Comment by dszlachta** [comment]
In my opinion we don't need this field. It is important to know our data when writing front-end code, not in the runtime. And we have Typescript typings right now. So yes, I think we should remove `types` field

**Comment by tjayrush** [comment]
The types field from the API generated data has been gone for about a month. Nothing has cropped up, so deleting.
