### ISSUE TITLE
Trouble with `yarn develop`

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-explorer#194]
Ro Ma — Today at 11:04 AM
What is expected yarn version for trueblocks-explorer develop branch ? (edited)

tjayrush — Today at 11:05 AM
We're running yarn version 1.22.10 on MacOs. Are you having trouble?

Ro Ma — Today at 11:08 AM
Default ubuntu 20.04 yarn does not work: 
00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one
 , but now installed new one and looks like its working, will update soon. Running 1.22.15 yarn version. (edited)

Ro Ma — Today at 11:26 AM
After running yarn develop: 
[1] /trueblocks-explorer/node_modules/electron/dist/electron: error while loading shared libraries: libxshmfence.so.1: cannot open shared object file: No such file or directory
[1] yarn develop:electron exited with code 127

dawid — Today at 11:28 AM
For the time being please use ‘yarn develop:ui’ instead. I’ll have a look at this error

Ro Ma — Today at 11:28 AM
Thnx !

tjayrush — Today at 11:30 AM
@dawid can we just change the script to not run anything and just print a message?
NEW

@dawid
For the time being please use ‘yarn develop:ui’ instead. I’ll have a look at this error

Ro Ma — Today at 11:47 AM
Just continued to debug it a little more: so after: 
 sudo apt-get install libatk1.0-0-dev libatk-bridge2.0-dev libgdk-pixbuf2.0-dev libgtk-3-dev
 I am getting this after running yarn develop: 
  The futex facility returned an unexpected error code , trueblocks/trueblocks-explorer/node_modules/electron/dist/electron exited with signal SIGABRT
 (edited)

@tjayrush
@dawid can we just change the script to not run anything and just print a message?

dawid — Today at 11:48 AM
Sure

@Ro Ma
Just continued to debug it a little more: so after:  sudo apt-get install libatk1.0-0-dev libatk-bridge2.0-dev libgdk-pixbuf2.0-dev libgtk-3-dev I am getting this after running yarn develop:   The futex facility returned an unexpected error code , trueblocks/trueblocks-explorer/node_modules/electron/dist/electron exited with signal SIGABRT (edited)

dawid — Today at 11:49 AM
Thank you for investigating this error. Hopefully I’ll be able to fix it after the weekend

**Comment by tjayrush** [comment]
I'm going to assume this is fixed since I was seeing it earlier, but no longer.

**Comment by Dawid** [comment]
I'm not really into doing anything about it. I'm not being paid for it and
it's not fun for me. And it seems like really boring stuff.
