### ISSUE TITLE
chifra serve: Invalid key (address) in list route.

### ISSUE THREAD

**Issue by tokerato** [TrueBlocks/trueblocks-explorer#244]
First time setup:

Chifra queries appear to be returning the correct data:
---
:~/trueblocks-explorer$ 
chifra state 0xa1e4380a3b1f749673e270229993ee55f35663b4 0x88e96d4537bea4d9c05d12549907b32561d3bf31f45aae734cdc119f13406cb6
blockNumber     address balance
1       0xa1e4380a3b1f749673e270229993ee55f35663b4      2000000000000000000000
---
chifra blocks 12345
{ "data": [
{
  "gasLimit": 5000,
  "gasUsed": 0,
  "hash": "0x767c2bfb3bdee3f78676c1285cd757bcd5d8c272cef2eb30d9733800a78c0b6d",
  "blockNumber": 12345,
  "parentHash": "0x4b3c1d7e65a507b62734feca1ee9f27a5379e318bd52ae62de7ba67dbeac66a3",
  "miner": "0xad5c1768e5974c231b2148169da064e61910f31a",
  "difficulty": 735512610763,
  "finalized": true,
  "timestamp": 1438367030,
  "baseFeePerGas": 0
}] }
---

Running chifra serve/attempting curl queries returns error:

curl http://localhost:8080/list?address=0xfB6916095ca1df60bB79Ce92cE3Ea74c37c5d359
{
  "errors": [
    "Invalid key (address) in list route."

curl "http://localhost:8080/blocks?blocks=4001001&uniq_tx"
{
  "errors": [
    "Invalid key (uniq_tx) in blocks route."
  ]

--
erigon@ETHerigon:~/trueblocks-core/bin$ ./chifra serve
2022/03/29 19:47:26 Server URL:       http://localhost:8080
2022/03/29 19:47:26 RootConfig Path:  /home/erigon/.local/share/trueblocks/
2022/03/29 19:47:26 ChainConfig Path: /home/erigon/.local/share/trueblocks/config/mainnet/
2022/03/29 19:47:26 Cache Path:       /home/erigon/.local/share/trueblocks/cache/mainnet/
2022/03/29 19:47:26 Index Path:       /home/erigon/.local/share/trueblocks/unchained/mainnet/
2022/03/29 19:47:26 RPC Provider:     http://localhost:8545
2022/03/29 19:47:26 Progress:         14483077, 14282457, 14282457, 14282457
2022/03/29 19:50:55 0 GET /blocks?blocks=4001001&uniq_tx RouteBlocks 105.213µs
2022/03/29 19:55:06 1 GET /list?address=0xfB6916095ca1df60bB79Ce92cE3Ea74c37c5d359 RouteList 52.26µs

As a result trueblocks-explorer is blank.

**Comment by tjayrush** [comment]
It seems like your documentation is out of date. Can you PLEASE tell me where you got those URLs so I can correct it?

For the first query, change `address` to `addrs`

For the second query, change `uniq_tx` to `uniq`.

On our installation (which is the latest `develop` branch).

If you would be so kind, can you please make sure you tell me where you found that API documentation? I'm looking here: https://trueblocks.io/api/

**Comment by tokerato** [comment]
frontpage of https://github.com/TrueBlocks/trueblocks-explorer

**Comment by tjayrush** [comment]
Thanks so much. I'll correct this now.
