### ISSUE TITLE
it knows about my custom chains but "options" doesn't let me switch to them

### ISSUE THREAD

**Issue by 1blockologist** [TrueBlocks/trueblocks-explorer#261]
There is a dropdown with four hardcoded chains and rpc endpoints as configured by trueblocks-core configuration file

and then there is the "options" section where nothing is an option at all.

how do I switch to my custom networks or at least change the RPC endpoint? I could mess up the mainnet configuration I guess, its rpc endpoint is accurate to what I configured

this is a bug. please advise

<img width="200" alt="image" src="https://user-images.githubusercontent.com/21366360/167525395-662eae0e-a49a-44a4-9f50-38b13621a1a8.png">

**Comment by tjayrush** [comment]
@dszlachta Do you have time to look into this?

**Comment by dszlachta** [comment]
@tjayrush I think we can make the list show options from the configuration file. We just need an endpoint in `serve` that would return it

**Comment by tjayrush** [comment]
I’m not sure which one, but I think the endpoint is `status` and it does deliver the entire list of configured chains found in the config files.  I’ll look it up and post here.

**Comment by tjayrush** [comment]
It's actually much easier than I thought. We already get the list of chains from the backend with this line: https://github.com/TrueBlocks/trueblocks-explorer/blob/master/src/ui/App.tsx#L76.

In fact, we use it in the Status panel at the bottom to make the list of available chains.

The only thing to do is use it when building the dropdown.

If you make a PR against develop, I'll merge it.

**Comment by dszlachta** [comment]
@tjayrush what about reconciliations, should we use `chain.symbol` there?

**Comment by dszlachta** [comment]
That's right. Okay, I should have the fix ready tomorrow.

**Comment by tjayrush** [comment]
I tested it. Works perfectly.

I found a bug in the server code for chains that we had not seen before, but that was an easy fix.

If you have no reservations, I'll merge it.

@1blockologist a fix is on it's way. Once this (https://github.com/TrueBlocks/trueblocks-explorer/pulls) gets merged, you will need to pull and rebuild the core, but it should work...

Should be merged by my tomorrow morning.

**Comment by dszlachta** [comment]
I see that your fix for `serve` has landed in `develop`, so I'll just merge this one. Let's release them today
