### ISSUE TITLE
Blank screen when first running explorer -- because of missing setting in .env file

### ISSUE THREAD

**Issue by steelep** [TrueBlocks/trueblocks-explorer#279]
Hi,

It is not clear from the documentation that the .env file needs to be updated, if you are accessing the trueblocks-explorer frontend from a browser on another machine. If you do not, it causes component connection failures. I suggest a revision to the README.MD to point this out.

![Screenshot 2022-07-05 at 23 22 50](https://user-images.githubusercontent.com/1321323/177740674-4514f67e-275f-4a25-9fcc-c32c9c7662a7.png)

Thanks

**Comment by tjayrush** [comment]
Thanks. Yes.

Note to self: This user seems to have opened the app without first having created the .env file. The docs should be more clear and instruct the user to copy the `.env.example` file to `.env`.

(I'm just noticing that the example file is hidden, which may be why the user didn't see it.)

Also, the `.env.example` file should have comments inside of it, so the user will know what to do with it.

Also, the README should tell the user to make the setting.

**Comment by tjayrush** [comment]
Perhaps the application itself could recognize that it has not `.env` and/or that the `.env` does not contain a valid URL to the chifra server and instruct the user to correct the missing value for the Server url.

**Comment by tjayrush** [comment]
The explorer repo has been closed, but we're still working on apps. More later on our blog.
