### ISSUE TITLE
I cannot install

### ISSUE THREAD

**Issue by MrNeth** [TrueBlocks/trueblocks-explorer#296]
I get permissions error when trying to clone repo?

**Comment by MrNeth** [comment]
> I get permissions error when trying to clone repo?

`❯ git clone git@github.com:TrueBlocks/trueblocks-explorer.git
Cloning into 'trueblocks-explorer'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

**Comment by tjayrush** [comment]
Can you try the solution described in the first answer here? https://stackoverflow.com/questions/12940626/github-error-message-permission-denied-publickey.

Also, a kind, gentle reminder that you should search the web before posting an issue to not only our repo but every open-source repo.

I understand, of course, that it's very confusing, so it's not a big deal, but it helps us (the developers) if you can do that prior to us having to spend the time. I'm sure you'll understand how difficult it would be if we had to search the web for everyone with a question.

And I do truly mean for this to be a kind, gentle reminder, so please accept it as such.

**Comment by MrNeth** [comment]
you are 100% right after many hrs trying to understand this repo and what it does im completely overlooked the SSH key! sorry to waste your time and thanks for the respone !

**Comment by tjayrush** [comment]
It's all good. Thanks for showing interest. Please let us know (in the Discord) if you have any questions.
