### ISSUE TITLE
6.0 Some fetches to backend need periodic refresh

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-explorer#43]
In the previous version we used a library for fetching data from the backend that allowed two things:

1) periodic refresh of the data (for example, every 14 seconds)
2) refresh of the data if the window goes out of focus and returns to focus (hidden by another window for example).

The library was called [SWR](https://github.com/TrueBlocks/trueblocks-explorer/blob/master/package.json#L58). Not sure we want to use that, but we need the same functionality.

https://swr.vercel.app

Please review this and consider using it since I'm already a little bit familiar with it. Although, I'm open to other suggestions for similar functionality.

**Comment by dszlachta** [comment]
The library is definitely nice, but it seems to have a lot of features for standard web apps (like handling slow network, etc.). In our new Explorer version, we have useCommand which basically does the same thing (but ignoring things that will not happen for local-first app). I'm pretty sure that the simplest solution here is to wrap useCommand into setInterval and useEffect and just put this mix into StatusPanel:

```
function StatusPanel() {
  const [status, setStatus] = useState({});
  const [loading, setLoading] = useState(true);

  useEffect(() => setInterval(() => {
    const [response, loading] = useCommand('status');
    setLoading(loading);
    
    // check if response status is fail, if no then we can continue
    setStatus(response.content);
  }, 13 * 1000), []);
}
```

Here is a nice article explaining it: https://reactgo.com/react-setinterval/
Later on, we may just build another custom hook to encapsulate this whole functionality, so we just write `state = useCommandPeriodic(interval, command)`

**Comment by tjayrush** [comment]
Thanks for this. I am going to try to do this on my own to get a better idea of how to code React.

**Comment by deeayeen** [comment]
https://github.com/TrueBlocks/trueblocks-explorer/pull/84

**Comment by tjayrush** [comment]
As per discussion in Discord:

Maybe you can look at is this: https://swr.vercel.app/.

The one thing I really liked about this was that it would cache the previous result from the polling and only reload if the new data differed. Another thing I really liked was that if the window went out focus, the query would automatically refresh when the window came back into focus.

 And one thing I thought about doing, but never did, was only really refresh the 'latest block' numbers on a polling basis. So, instead of the whole status panel displaying 'loading' only the block numbers would 'flash' or 'spark' if they change. Much more subtle than the loading. But we can work on that later.

**Comment by tjayrush** [comment]
@deeayeen I am going to close this issue since you've completed it for 'status'. I do have a few small issues, but I will write different issues for those.
