### ISSUE TITLE
Remove the 'Entities' menu item

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-explorer#48]
This has always been a very confused idea. It was meant to allow the end user to specify a group of related addresses and look at them in a combined view. I think that idea is still valid, but may not warrant a top level menu item. It may, but my guess is that it doesn't. In any case, in order to move forward, I want to remove it. We can always add it back later.

**Comment by dszlachta** [comment]
Sure, but what should be the default view then?

**Comment by tjayrush** [comment]
I never got around to writing it in the old explorer, but I think there needs to be some sort of 'overview' or 'dashboard' view where total holdings of all monitored accounts shows up. Recent history. Related accounts. Here's a very bad image of that imagined, future page:

<img width="1596" alt="summary" src="https://user-images.githubusercontent.com/5417918/119254687-bcf2b800-bb85-11eb-8558-030319350c2c.png">

**Comment by tjayrush** [comment]
Entities has been renamed Collections.
