### ISSUE TITLE
7.0 Hitting escape on a very long running command should quit the request

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-explorer#51]
I modified one of the TrueBlock Core tools to sleep for 10 seconds as a way to test the 'Loading' component.

It works well.

However, I wanted to cancel the request by hitting the `escape` key on my browser. I expected the application to cancel the request and return control to the user, however, it simply continues to spin the spinner.

Question:

1) Should the user be able to able to cancel the request?
2) Can we fix our application so it does that?

**Comment by dszlachta** [comment]
Good idea, it would be useful given the size of data we are working with. I will be adding a code to handle keyboard shortcuts this week (for the tables, but can be also used elsewhere). We would also have to implement AbortController (https://developer.mozilla.org/en-US/docs/Web/API/AbortController) to make the requests cancellable and refactor useCommand to return `cancel()` function, which should not be too hard
