### ISSUE TITLE
Reproduce Status Panel in version 2.0

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-explorer#54]
In version 1.0, there is a 'status' panel whose display I like. It's informative and looks professional. I'd like to re-create it in version 2.0. Currently, we query the data but we only present it as formatted JSON data.

**Comment by deeayeen** [comment]
https://github.com/TrueBlocks/trueblocks-explorer/pull/58

![image](https://user-images.githubusercontent.com/35680780/119916443-37984a80-bf6d-11eb-95e3-008d9946d932.png)

**Comment by tjayrush** [comment]
I'm closing this as it's completed at least far enough along to allow for future issues if they arise. Nice work. Thanks.
