### ISSUE TITLE
4.0 Mechanism for handling errors from the backend

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-explorer#63]
I was working on one of the subviews (Transactions under Explorer) and I made a mistake in the URL to access the API.

I used http://localhost:8080/transactions?transaction=latest when I should have used http://localhost:8080/transactions?transactions=latest (missing 's').

The front end didn't fail in an obvious way. Dan suggests it should report an error through a 'Toast'.

But this is a bit of a larger issue...

We need a way to respond to problems with the back end in general. There's a number of different scenarios detailed in this issue: https://github.com/TrueBlocks/trueblocks-core/issues/1619.

This issue tracks the need for a 'methodology' to handle errors (not the solution to each issue -- just an overall mechanism to handle errors from anywhere in the code).

I can handle each individual error using the above issue.

Related #50

**Comment by deeayeen** [comment]
https://github.com/TrueBlocks/trueblocks-explorer/pull/83

**Comment by tjayrush** [comment]
I am going to close this issue in favor of issue #91.
