### ISSUE TITLE
Issues with keyboard control of table

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-explorer#90]
Here's a bunch of small issues. Not sure if you'd rather have them in individual issues or all together. If you want me to separate these out, let me know.

- [ ] Key strokes on any page that contains a table should take focus to the table right away -- in other words, I don't want to have to put the mouse over the table -- hands on keyboard at all times
- [ ] First arrow down puts blue line under row 0. Second arrow down puts highlighted row on row 1. There should only ever be a highlighted row -- never a row with just a blue line. On second thought, this appears to be an issue with the row when the mouse is over the row not the top line.
- [ ] The actions to the right of the display need to be highlighted as well (the whole row needs to be highlighted).
- [ ] Double blue marks above and below the Tags column should not be there. Fields should not be highlighted -- only entire rows
- [ ] When at the bottom of the current page, if user hits down arrow, switch to next page (if not on last page)
- [ ] When at top of page, if user hits up arrow, switch to previous page (if not on first page)
- [ ] Home should go to page 1, record 1.  Currently it stays on the current page, but goes to record 1 on the current page.
- [ ] End should go to the last row of the last page (be careful around off-by-one errors when number of rows is even division of pages)
- [ ] Left / right key correctly switches pages, but the first row in when that happens should be highlighted. It currently requires a page down to highlight it.
- [ ] Two consecutive end keys toggle between last row and second to last row (on page -- should be in entering table)
- [ ] Let's disable expanded rows for now -- keep the functionality there, but hide the icon and ignore the enter key -- for now -- we can revisit this.
- [ ] If no row is selected (highlighted) and the user presses the end key, the first row is selected. If user hits end key again, last row on current page (should be last ever row) is selected.
- [ ] Two consecutive presses of home key causes selected row to toggle between row 0 and row 1

**Comment by deeayeen** [comment]
All updates addressed
https://github.com/TrueBlocks/trueblocks-explorer/pull/92

> Here's a bunch of small issues. Not sure if you'd rather have them in individual issues or all together. If you want me to separate these out, let me know.
> 
> * [x]  Key strokes on any page that contains a table should take focus to the table right away -- in other words, I don't want to have to put the mouse over the table -- hands on keyboard at all times
> * [x]  First arrow down puts blue line under row 0. Second arrow down puts highlighted row on row 1. There should only ever be a highlighted row -- never a row with just a blue line. On second thought, this appears to be an issue with the row when the mouse is over the row not the top line.
> * [x]  The actions to the right of the display need to be highlighted as well (the whole row needs to be highlighted).
> * [x]  Double blue marks above and below the Tags column should not be there. Fields should not be highlighted -- only entire rows
> * [x]  When at the bottom of the current page, if user hits down arrow, switch to next page (if not on last page)
> * [x]  When at top of page, if user hits up arrow, switch to previous page (if not on first page)
> * [x]  Home should go to page 1, record 1.  Currently it stays on the current page, but goes to record 1 on the current page.
> * [ ]  End should go to the last row of the last page (be careful around off-by-one errors when number of rows is even division of pages)
> * [x]  Left / right key correctly switches pages, but the first row in when that happens should be highlighted. It currently requires a page down to highlight it.
> * [x]  Two consecutive end keys toggle between last row and second to last row (on page -- should be in entering table)
> * [x]  Let's disable expanded rows for now -- keep the functionality there, but hide the icon and ignore the enter key -- for now -- we can revisit this.
> * [x]  If no row is selected (highlighted) and the user presses the end key, the first row is selected. If user hits end key again, last row on current page (should be last ever row) is selected.
> * [x]  Two consecutive presses of home key causes selected row to toggle between row 0 and row 1

**Comment by tjayrush** [comment]
Two remaining issues:

**Issue 1**
Start the app fresh.
Go to Names / Addresses table
Hit down array -- works correctly.
Keep hitting down arrow until the bottom of the current page -- does not go to next page
Hit next page (right arrow), does not page
Hit END - goes correctly to the last record
Hit HOME - goes correctly to the first record
Now hit right arrow -- goes to next page
Hit HOME -- now hit down arrow until last item on this page, it goes properly to the next page
(In other words -- paging by keyboard doesn't work until one hits HOME or END key)


**Issue 2**
Go to second page
Hit up arrow
Properly goes to previous page, but the first record on the page is highlighted, not the last row on the page as it should be

**Comment by deeayeen** [comment]
https://github.com/TrueBlocks/trueblocks-explorer/pull/94

Issues 1 and 4 fixed in the above PR

**Comment by deeayeen** [comment]
Issue 3 now solved on https://github.com/TrueBlocks/trueblocks-explorer/pull/94 as well

**Comment by deeayeen** [comment]
And with some fiddling... Issue 3 now solved on #94. All issues should now be addressed

**Comment by tjayrush** [comment]
Done.
