### ISSUE TITLE
Enable web socket's console log in new UI

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-explorer#95]
If you run the old UI, you will see that the backend API server communicates progress to the front end through web sockets which feed into a component at the bottom of the display I call the 'console.'

This 'feedback' to the user, which gives information about what's happening on the server, is important to me, and I would like to re-enable it in the new UI.

The 'feeding of progress' data is already implemented and working in the back end, so this issue is just re-enabling it on the frontend. There shouldn't be any backend work needed as that code has not changed.

Steps:

1. Run the old version of the UI to see how the console component works
2. Read the code related to that component in the old version and either copy it over to the new version or re-implement it.

**Comment by deeayeen** [comment]
https://github.com/TrueBlocks/trueblocks-explorer/pull/106

**Comment by deeayeen** [comment]
Anything else required on this one?

**Comment by tjayrush** [comment]
Not for now. In the future, maybe.
