### ISSUE TITLE
9.0 More issues with keyboard control on tables

### ISSUE THREAD

**Issue by tjayrush** [TrueBlocks/trueblocks-explorer#98]
**Issue 1**
Go to names table
Hit home
Hit up arrow key
Should do nothing....scrolls to bottom of current page instead.

**Issue 2**
Rows per page control captures keyboard control if changed.
- On any page, confirm that keyboard control works
- Change the number of rows per page control (notice it captures keyboard control)
- Hit next/prev key or nextpage/prevpage. Row selection does not work
- Suggestion: after changing rows per page value return to first page and select the first row in the table.
- Note that the same does not happen if one clicks on page link directly.

**Issue 3**
Hit the home key
Hit down arrow once (selected row is now second row on page)
Hit next page key
The selected row is correctly the second row on the page. All good
Hot the home key again (first row is selected)
Hit next page key
Fourth row on page is selected -- would have expected first row to be selected.

**Comment by deeayeen** [comment]
https://github.com/TrueBlocks/trueblocks-explorer/pull/99

**Comment by tjayrush** [comment]
Two very small issues that can be fixed later:

1. Hit end key twice, see toggle between last and second last row
2. Go to page four or five. Scroll down four or five lines. Hit previous page key. It properly stays on the `nth` line as it should as it scrolls through pages. The first time it gets to the first page, it should stay on the `nth` line (as it does). If user hits previous page again, while on first page, it should go to first row of first page to signal no more movement is possible.

Do those two more things and I will close this.

**Comment by deeayeen** [comment]
Fixed in https://github.com/TrueBlocks/trueblocks-explorer/pull/100

**Comment by tjayrush** [comment]
All fixed.
